data = "weseswseswesewseseseswewswseswnenwsese;nwswwwnwwwswswseswseswwsewswnewsw;wnwnwsewwnwenwnwnwwwnwnwnewnwswne;nwnwnwewnwnwswwnenwsenenwnwnwnwenwnwnw;swswewswewneseeseswseewwsewnwne;swwnenenenwswsweneswswswswneewwsewnw;neswewseswswseswswswswneswwswsenewsese;nwwnenenwwnwnewnwsenenwsenwse;eswwnwswswswwneswwwwewnwnwswsewse;sewseneeesesewseseswnesesewseseeese;nwweneseeswnesewsesenwsese;swswswneswswswswwsw;nwnwnwnwnwswnwwnwnwnenwewnwsenwnwese;enwwneneseseswewneeswsenwneswneseenw;enwswesenwnwseenwseseeeswnwnwneseswnwe;eswwwswneneesenwenenenwswswnese;wnwweseswnwneenenewswwnweswwsesw;nwneswneeeswewwneseneseswswwwsenenw;nwweweeeswnwswesweneenweneeew;swseswswwwseswwwwwwwwnwewwne;nwsewsenwnwwwnenw;neswswneeeeeeneenwwnwneewseswwse;seesesewseswenwsesewneeenenwswnesew;eeenweeesweeeee;swnwnwnwswsewnenewswwwweswwsewswe;seneenwnwwnwswwnwnwnwwnwnwewwnwnw;swswneenenwwewswnwwswnewwnwswwww;neswenenwnwnenenenesenwswswnweswwsewnenw;eeseeeenweeseesesenwe;nenwneneneewneesenesenenenene;eenesewseseewe;nwnwwwwwwswswwneweeewswwwww;wwnesenweseneneeeneswswswnesenwnwe;swseseswenwsesesenweeswsesesewswnwnwnw;newswnweswswseswnenenene;neneeneneeeneeeswneeneesewwnwsenw;neeneswwnwnenwwneenwneseswneenewe;nenwswseswneswswswneswswswswwsewsweseww;sesewseeseesesesenewsenwnwswewsenew;swswneeseswswwwwswwneswswnwswswswsenw;swswswseswswneswswseswseswsweww;swwneswneswwseseenwswswswswswsenwswswsw;seswseesenwewsesesw;sweneswnwenewneseneenenwnwneseswseenw;nwnenenwnwnewenenwsweswne;wwnewwwwwwewewnwwwwnesewse;nwnwsewnwnwweswnenwnw;swneeneneeneneneneeenenee;eneweseeesenwwweeeeeeweene;nenwnwswnwnwnwnwnwnwnwnwnwnenwnwsese;nwneneesweneeeneenenene;eneesweneneenenwneesenwneneeneswnw;seswnwswneswswnwswswseseseswsesenwseesese;swwenwenwnwnwnwnwswwnwneswwnwneeenw;wseeseneneswwwnewnenenenwswwswswwsw;eneenwnwnenwwnwnwnwnwnwswnwnwnwnwsew;nwnwswswnwnwnwnwweweenwwnwnwnew;swenwsenenwswwneenenenwswnenenenenwnenenw;swnenwwneseswswwswneswwnewswswesenw;nenenenenwnwnesenwswnwenenwnenwenwneswne;wenenweeswsweswnwseswneeneneswswnw;seesesesesweseneswswswwnwwswsenewswsw;newwwsenwnwswwwnweswnwnewnwwsenese;senwwnwnenwnenenwnenenwnweenwnewwnw;eneswwseenenwnenwswswseeneenesesew;eseeeswwenwenweswseneeenenenene;seeswnweeswneeeeneswneneneneeeew;sewswwswwswneswseswneswnenwwswswseww;seseenwseswsesenwnwnwwseseesesese;swswseneswneswswswswsweswswswwswswnwsw;neeseeseneneenweewe;swwsenenenenwneneneneneneneeneneneswne;enwnenwnwneewswseenenenwswswnwnwenwnwsw;neswenwneeeeeeee;neesenesewswnwswsesewswseswsese;nwnwnwnewsenwnwsenesenwneswnewnenwnenw;eneswsenenenewene;wsenwnwnenwnwswwnwnwenwnenwswsenewwnw;nenewswneswsenwenwnwnesenwnwneeswneene;swneseseneswnesenesewwswesewseseswse;eneeewnewwwswnewesenwseseweswsene;neesweneswswneeeswneneeeeneenenw;wsenwnwwnwnwnwnwwwwww;sewwsewswwwnwwnwenwwnewwnwnwe;neeneeneeswneeeneee;swseneseneseseswnenwswneswenenwseswww;seseswswswwsewswswnewsesweneswnwswesw;seswswsenwswneswswswnwwsewnwwwswwse;swsenwswnwwswswnwsenwneneenesenwnenee;swnwswsewswswnewswswswswseswswswseswe;neeeeneneneneneweeene;sesweneseswnwneswswnwwnwneewenesee;sewswsesenesewseseseneswseseswnesesesw;nwswwswwswswswswswwneswswwswe;enwnewnwswnenenwwseswnwswsenwnenwene;esesesenweseeseseseeenwseseseswsenw;neeneneneswseewneswnwnenwnwnesenenesee;swswwwswswswswesww;wwwswnwswswenesewenweewneenwene;eseeenewwwwnenenewwneneneseewsese;wswsesweswswswnewswnw;neeeeneenesweeeswswneeeenwsenw;sesesenewnwswsenwnwnwwnwnwwwwseswsese;seeesesweeeseeenwenwsweneseewee;wneweswswwneenwwwsenewsewwwsw;nenewneneneneneenenenesewnenenene;seswswnwnenwnwnenwnenenenewnesweeswse;swesesesewnwseesenwswnwe;swewswwesesewswwnwweneenwswsww;seeswewswnwseeseseseesenwnwnwenwseese;neneswswwwseneswwneswswswswwswsesesw;seenwweeswenesweneeeneeeenweene;swwesenwswwenenwneewwsesww;nwwnwneeenwswnwenwnewwwnwnwswnwnw;neswneneneneneeneeenwneneswnenewnesene;eseseenesenwswsesenwseseeseseeswnese;neseswswenwnewneneswnenwneseswsweswsww;swsenwseneswswnesweeswswswswswswswswsww;eseeewseeeseneseeeseeewneseww;nwnwswwnwnwnwnwnenwwww;wwwwwnwnwwwneseww;seeswseneseeeseseseswwneeeseesesenw;wnwewnwnwwwnesewwnwnw;eesewsenwsesenesee;sesesewesweneewnweneesesese;nwseewseneswseseseeseewsenenweswese;wneswwswnenwwswseeswwwnw;nesesesewneseswswwswswswswesenwnwnwsesw;nwnwnenwnwnwnewnwwswnwewnwnwswenwnw;swseeswwnwnwsenenenwswwswseseswswsesesesw;swseseseeneewsesesewneesewseseeese;sewwsesenwwewnenenwneneenewnwnwe;nwwenwwnwnenwnenwnwnwsene;nwenwnwewnwwesesenwswwnwnenwwwne;senwsewwnwwwwwseenwswwnwwneese;wwwswwnwswsewewewwnewewswsww;swneeeenenwnwneswese;neswwwwwnweseenwneenwswswseeswnw;eswnenwswneeeswseneswneenenwnenwee;nwnewneswswwneeseseseswseneeneeseesw;neeneeeeweneswenweseswee;eseswnwwswnwsweseseswseswswsesesweswsw;seenwenwseswsesewweseseseweswse;eenweseswewneswwnwwenwwwenwsw;swseseswwwswwnenewwswswnwnesesw;wwnwswwswsewneneewnwnwwswnwwwwse;nenenesenenwnwnenenw;nenwwneneseneneswneswnenenweneneswne;nwsenewwnwnwnewwwswswswseeswwwswsee;swnwnwnwswneseeenesweeewesweeeee;swseseenwswswswwnwswwswsweswse;nwswnenenwneswswnenenwswnwneswswnweneneene;swswenwsenesewswswnwwenwswnwneswswswsw;wwswswnwwneswswswneeswsw;nwsweswwwwswwswwnewswweswsewswne;seewseswswnwwswsenenesweeswswwswnwnenw;neenwswseeswswsweseeneneeneewsewe;weenwsesesenwnwseseswseseseswnesesee;seswswseswswswnewsesw;nwnwnwwnwnwnwnwnwenwnwnwnw;neswneswseneswneneneneneneneewneneenw;swwnwneswnwswswwswswswsesewneeswesee;nenwnewnesenwswnwnenwnenwe;esenwswsesenesewseswseseswseswsw;eseweeeeewneeeeeeewene;seswnwneswswwseswsewsweseswswswseswse;nwwnwewwnwwnwswnww;nwseseswseswswswswswsweswswsw;enesenesenewswsenwneswnenwnewnwnwnenwnw;seswswnwneswsweswswswswswnwswswweswswesw;wseswswwwwsenenesweseeseswse;nwnwnewwenwnwswseew;nwwnwsenwnwnwnenesenwnenwnwnenwnwnwnwse;wwnwsewnewwsewnwnenwsenwwwwnwww;wwwewwwwwwwwwwwswnwe;seseesweenwenwsenwswsenwseeeseseswese;swwenwnwnwnwnwnwwnwnwnww;nwnenwneneseneneneswenenenenwnwsenwnew;nenwsenwnenenesenenenenenenwnwnwneseww;nwwnwnenenesenenenesenenwnenenenesewe;neneewneswnwsewnenenwnene;nenwneewswnwnwneneewneneneenwnenenw;nwwwnwwnwnwseswnwwwsenwwneswnewewne;esweneenenwsewwswswswswwseswsewnwne;wseenwseswnesenwse;eeeswenwesenesenwewswne;neswseseseneswseswseseneswseseswsenesesese;wsewewwnewwnenwsenewwwwswswsw;wneeeswewsesenenwsewnwsewnewseese;swnweewnwwseeswnenwseswneswwnesese;sesenwewsesewswsweneneseeseeesene;wnwenwwwnwewsewwwwswsewwww;seneenenwnweeeeeeneeseenwnwswse;wsenewwwwwnwwwnwnwnww;nenwnwenwwwnenewwneenenwesenene;seeeswsweseesewenweeseseeneenee;sesewenwseeeeseewswnweeeseeenw;swenwnwswnwnwseeneswnwnene;swswswwswneesewswwwneeneeweswsw;swwnweeswnesenenweseseeesesewseese;sweseswwwswwneenwwwswe;wneneneeesenenenwneseeneneneeneswne;swwesesewneswwenwwswwwwwwwwnwsw;swenwswswswswswwwwnwnwnwswewswswee;senwswnwseeeneeswse;swswnwesweswswsweswswswwswnwnwne;neswneeneneneneneneeneene;eneseeseeswenweeweseseswseeenese;seswnwseseswswenesenenesewsewswswswse;wsesenwneseseseew;swwwswwewswwswsww;nwswswnwswswsweswsweswswewsenwswnene;eeeeeewnweeeweeseeswnwneseee;nwwwnwnwwsenwnenwswenwnwnwnwnwnenwnwe;seswsenwnwwseeseseneeswswswswswswnenw;swwneeeeenenweswe;wwwwnwwwnwswnenwsewwewww;swnenwnenwnwnewswnwnwenenw;seewswsesenwswneeee;nwwwewwwenwwwwweswwwnwnwnwse;wwnwwwswnwewwwswwswnwenewww;seswnenwneswnwsweenwnweenwwwweswnw;neswneseenesweenenenew;nenenwwneneneeeneneenenwswewesweene;swswswswswneswswswnwswseswswwneeswesw;seeweeeeseseeneeswnwewnwesee;swnwewswswnwswneswswswsesweneswswswsw;swnewneswnwswseswswswswsweswswswneswsw;swnwswneneneewnwwenwse;sewwwnewwswwwwwsw;swnwswnewnwsesewsewnenwnwsenwsenwenw;nwnwnwnwsenwsenwnwnwnwnenwnenwnwswneswnwnw;senesesesesesesewsenwswseseneseeseswwse;sesenenweneseseseseswwnewseewsenww;wneneswnenenenenenesenenenenenenesenwnw;swswneenwnwnwnwwnwnwnwnwnenwnwsenwsenwnw;wwnwwneswswwwswswswswswesew;wwnwseswnwnewwswwwewsewwsewene;wswseeswswswswswnwwneeswswswwwswswsw;wwnewesesewwseenwnwswnwnwnwnwnwse;neeneswewwswneswnenenenweenewnenwsee;swenwnwsesweenweeeneneneswewseese;sewwseweseseeseseneseesesenwnewse;nenenwnwneswneneneneseeneneneswnenene;newseeeneneeeeneeneenenw;neeneneswswnwnwneneneneseneesewnwnene;seseenwseseeswseneseswsenwseesesesee;swswswsesenwswnwswseswneswseswswswseseswnw;eneneneneenwesweweeeeswwenese;enenwweeneneneneswswnenenenenenenene;sewswswnwswswneseseneneswswseswseswswsw;sesesenwwnwnwwnwwwwenenwwnww;seseseswswswseenwseseswsweseenwnwsesw;wnwswseswsenwsesenwnwesesweseesenenese;sesesenwseseseswseseseneseesewseswnww;seswseeseswnwnwseewenwswseeseswseswse;seseswseneswneenwwseesenewswnwswwswse;wnwneneseswnenewnwnenwneneenenenewsenene;neneseseeeewwewsweeenwnwneswee;nwwwewwewww;newnwswwesesewnenwneswnewnwseneesew;nwwwwewewwswwnenwsenwnwnwnwwww;neseneswnenwweeneseewswseeneeew;newwsenwsesesesweseewseseseneseseew;neneneswewneneneneeeewnenesene;enenwswseeneseseeseweseee;wnenewwswewseeswswwnwwswwwwsw;seswnwnweenwsweenwneseeneeenenwneswe;newwwwswswneswwwswsww;wwwwsenwswwnwewneswwww;neswnenwnenenwnenwswnenenwswnenwnw;wsesenenwnenwnwnwnwneswwnenenwnwnwene;neswswwwwnewswswwswswwnwsenewnwswee;eswwsenenwneeeseseweeeswswenese;newseenenweesweeseesewsesenwseesw;neswswsenesweseswwwwswsweeswsenwswsw;swnwneswnenewenenenenenwenwneneenesw;esweswswnwswswsewnweeewwwseeswnw;nwnwwseweswnwswnwwewnesewwnenenwnw;senwnwsenwnwnwnwseswwnwnenwnwnwnwenenw;swnewswwwwwnewwwwnwneewwwsew;neneneeeseneneneesewswewneeenee;wswsenewneenesewnenwnenwsenwneswswnene;neewwnwnenwnenesesenenwnenwsenenwneswnee;seswnwneenesenwnenenwswnewneneneenee;nwnwwnenwswwwnenwnwnwneswnwswnwnwsenwnwne;swwwnewsenesenwsenewseeswnenesenwwsw;senwseseseneswseenwwwse;seseswseseseseseseswswseenwswsesenw;nenesenenwswwsewnwswnwneneeewnwene;swswswwswswswswswswwneswsw;sweneseesenwesewnewnwseeseswnwesese;nwnwswswswseswswsweswsw;eswswwswswwnwswwswwswswneswswnwsesw;newwwwwwwewwsenwnenwewsenenwsw;nweswweenwnwswnwenwwnwswnwnwnwnwnwnw;senwwswnenwseswswswnewneeswwwww;senwseswswnweneeswseswswwseswneswswswsw;weswwsewnweeewweneswnesewsene;neeswswnwnwnwswnwswneewnwnwnwnwswnenww;nwswwneewnesenesenenwnenenenwnwnwnwnenw;sweseeneseeneswenwneswswnwesee;nesewnwnwwnwnwnwnwnwnwnwnenwnwsenwnw;newneeenweeeeneneseene;wesesenwneenenwneswwneneenweswsene;eswnwswnwsenesweneswswsweswswsenwswsesw;swsesenwseswswseswswewsenwswsesene;weseeseeswswweseeneseseneeseenwne;wswswswswwsenwswnewneswneswswwsewwsw;eseswnwesenwnwwnwswnwsweneeeneesesew;wnwwswswwwnewswsenwswswsesweswnww;eeeneeneswewseeeneeweneesww;wnenwswwseewwswnewwnewwsenwnwsew;nenwswenenwsenenwsenwnwnwnenewnenenwswsw;neswnewweeeeeeeneneenenenenwsee;ewnweeeeswswseeeenweeeeenwe"

easymode = "sesenwnenenewseeswwswswwnenewsewsw;neeenesenwnwwswnenewnwwsewnenwseswesw;seswneswswsenwwnwse;nwnwneseeswswnenewneswwnewseswneseene;swweswneswnenwsewnwneneseenw;eesenwseswswnenwswnwnwsewwnwsene;sewnenenenesenwsewnenwwwse;wenwwweseeeweswwwnwwe;wsweesenenewnwwnwsenewsenwwsesesenwne;neeswseenwwswnwswswnw;nenwswwsewswnenenewsenwsenwnesesenew;enewnwewneswsewnwswenweswnenwsenwsw;sweneswneswneneenwnewenewwneswswnese;swwesenesewenwneswnwwneseswwne;enesenwswwswneneswsenwnewswseenwsese;wnwnesenesenenwwnenwsewesewsesesew;nenewswnwewswnenesenwnesewesw;eneswnwswnwsenenwnwnwwseeswneewsenese;neswnwewnwnwseenwseesewsenwsweewe;wseweeenwnesenwwwswnew"

easymode2 = "nwwswee"

# for at lave hexagonalt grid, er alle rækker forskudt således:

# 1:       -1  0  1  2
# 0:     -1  0  1  2
# -1:      -1  0  1  2
# -2:   -2  -1  0  1  2

x = 0
y = 0

fliptiles = data.split(";")
flipped = {}

for i in range(len(fliptiles)):
    fliptiles[i] = list(fliptiles[i])
    index = 0
    while(index < len(fliptiles[i])):
        if(fliptiles[i][index] == "e"):
            x += 1
            index += 1
        elif(fliptiles[i][index] == "w"):
            x -= 1
            index += 1
        elif(fliptiles[i][index] == "s" and fliptiles[i][index+1] == "e"):
            if(y > 0):
                x += 1
            y -= 1
            index += 2
        elif(fliptiles[i][index] == "s" and fliptiles[i][index+1] == "w"):
            if(y <= 0):
                x -= 1
            y -= 1
            index += 2
        elif(fliptiles[i][index] == "n" and fliptiles[i][index+1] == "e"):
            if(y < 0):
                x += 1
            y += 1
            index += 2
        elif(fliptiles[i][index] == "n" and fliptiles[i][index+1] == "w"):
            if(y >= 0):
                x -= 1
            y += 1
            index += 2
        else:
            print("Error whilst reading input...")
    loc = ",".join([str(x),str(y)])
    if(loc in flipped):
        flipped[loc] = (flipped[loc]+1) % 2
    else:
        flipped[loc] = 1
    x = 0
    y = 0

finalsum = 0
listflipped = list(flipped)
print("Placering af alle der har vaeret flippet mindst én gang: ",listflipped)
for i in range(len(listflipped)):
    finalsum += flipped[listflipped[i]]

print("When done: ", finalsum)


# 186 er too low...
