CC=gcc
CPPFLAGS=
CFLAGS=-Wall -std=c99
LDFLAGS=
LDLIBS= -lm

testdoc: exam_e20_question15.o exam_e20_question16.o exam_e20_question17.o exam_e20_question18a.o exam_e20_question18b.o

.PHONY: clean

clean:
	-$(RM) testdoc exam_e20_question15 exam_e20_question16 exam_e20_question17 exam_e20_question18a exam_e20_question18a *.o
